"""Edit typo in ProfileModel

Revision ID: 0798225572b0
Revises: 622dd12a4878
Create Date: 2023-03-01 17:53:39.243207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0798225572b0'
down_revision = '622dd12a4878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_birth', sa.String(length=10), nullable=True))
        batch_op.drop_column('data_of_birth')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_of_birth', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
        batch_op.drop_column('date_of_birth')

    # ### end Alembic commands ###
