"""Added profile picture field

Revision ID: 1a417b91e236
Revises: 47f12a6a517f
Create Date: 2023-02-22 17:57:46.156105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a417b91e236'
down_revision = '47f12a6a517f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_picture_file_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('profile_picture_file_url')

    # ### end Alembic commands ###
