"""Edit ProfileFields class name

Revision ID: 4f692db26717
Revises: b3cb58495525
Create Date: 2023-03-02 16:48:01.475134

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4f692db26717'
down_revision = 'b3cb58495525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('public_fields',
               existing_type=postgresql.ARRAY(postgresql.ENUM('first_name', 'last_name', 'data_of_birth', 'profile_picture_file_url', 'city', 'address', 'phone_number', name='profilefieldsenum')),
               type_=postgresql.ARRAY(sa.Enum('first_name', 'last_name', 'data_of_birth', 'profile_picture_file_url', 'city', 'address', 'phone_number', name='profilefields')),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.alter_column('public_fields',
               existing_type=postgresql.ARRAY(sa.Enum('first_name', 'last_name', 'data_of_birth', 'profile_picture_file_url', 'city', 'address', 'phone_number', name='profilefields')),
               type_=postgresql.ARRAY(postgresql.ENUM('first_name', 'last_name', 'data_of_birth', 'profile_picture_file_url', 'city', 'address', 'phone_number', name='profilefieldsenum')),
               existing_nullable=True)

    # ### end Alembic commands ###
