"""Simplify EducationModel

Revision ID: 506765f5a1af
Revises: 7ed985b22045
Create Date: 2023-04-15 17:31:36.166531

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '506765f5a1af'
down_revision = '7ed985b22045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.alter_column('fields_of_study',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('diploma_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('diploma_file_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.alter_column('diploma_file_url',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('diploma_number',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('fields_of_study',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=100)),
               nullable=False)

    # ### end Alembic commands ###
