"""User models major refactoring

Revision ID: 622dd12a4878
Revises: a6be2607f845
Create Date: 2023-03-01 15:38:26.803100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '622dd12a4878'
down_revision = 'a6be2607f845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('admin_owner_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('admin_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('employer_owner_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('employer_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('job_seeker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('job_seeker_owner_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('job_seeker_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_column('owner_id')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint(None, ['id'])
        batch_op.drop_constraint('profile_owner_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['id'], ['id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profile_owner_id_fkey', 'user', ['owner_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('id')

    with op.batch_alter_table('job_seeker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('job_seeker_owner_id_fkey', 'user', ['owner_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('job_seeker_owner_id_key', ['owner_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('employer_owner_id_fkey', 'user', ['owner_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('employer_owner_id_key', ['owner_id'])
        batch_op.drop_column('id')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('admin_owner_id_fkey', 'user', ['owner_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('admin_owner_id_key', ['owner_id'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###
