"""Major UserModel refactor

Revision ID: 6f2b0c35e469
Revises: 889176b52a79
Create Date: 2023-02-28 10:46:26.599834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f2b0c35e469'
down_revision = '889176b52a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.Column('roles', postgresql.ARRAY(sa.Enum('ceo', 'recruiter', name='employerroles')), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    op.create_table('job_seeker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_changed', sa.DateTime(), nullable=True),
    sa.Column('preferred_contact_method', sa.Enum('any', 'phone', 'email', 'pm', name='contactmethods'), nullable=False),
    sa.Column('roles', postgresql.ARRAY(sa.Enum('talent', name='jobseekerroles')), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('job_seeker')
    op.drop_table('employer')
    # ### end Alembic commands ###
