"""Added is_deleted to BaseModel

Revision ID: 7ed985b22045
Revises: 935d7bb96c3a
Create Date: 2023-04-15 15:52:35.904940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ed985b22045'
down_revision = '935d7bb96c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('awards_and_achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('job_seeker', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    with op.batch_alter_table('work_exp', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_exp', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('requirement', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('reference', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('job_seeker', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('employer', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('education', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('certificate', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('awards_and_achievements', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
