"""Major UserModel refactor

Revision ID: 889176b52a79
Revises: a58c049c2124
Create Date: 2023-02-28 10:39:04.874370

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '889176b52a79'
down_revision = 'a58c049c2124'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent', schema=None) as batch_op:
        batch_op.drop_column('preferred_contact_method')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('talent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_contact_method', postgresql.ENUM('any', 'phone', 'email', 'pm', name='contactmethods'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
