"""Added date of birth to ProfileModel

Revision ID: 8af2a73bb6bc
Revises: b6f4af47ca31
Create Date: 2023-02-26 18:18:43.346756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8af2a73bb6bc'
down_revision = 'b6f4af47ca31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creator_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('data_of_birth', sa.String(length=10), nullable=True))
        batch_op.drop_constraint('profile_user_id_key', type_='unique')
        batch_op.create_unique_constraint(None, ['creator_id'])
        batch_op.drop_constraint('profile_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['creator_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('profile_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('profile_user_id_key', ['user_id'])
        batch_op.drop_column('data_of_birth')
        batch_op.drop_column('creator_id')

    # ### end Alembic commands ###
