"""Edited CVModel

Revision ID: 9c15a99a1c24
Revises: 9d7cec38f511
Create Date: 2023-04-12 15:29:59.161926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c15a99a1c24'
down_revision = '9d7cec38f511'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cv_requirement_association')
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requirements_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'requirement', ['requirements_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cv', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('requirements_id')

    op.create_table('cv_requirement_association',
    sa.Column('cv_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('requirement_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cv_id'], ['cv.id'], name='cv_requirement_association_cv_id_fkey'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], name='cv_requirement_association_requirement_id_fkey')
    )
    # ### end Alembic commands ###
