"""Major refactor of user model

Revision ID: 9fc4feead9e7
Revises: 48c9de4d124d
Create Date: 2023-02-27 20:33:51.182726

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fc4feead9e7'
down_revision = '48c9de4d124d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('profile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))

    op.create_table('profile',
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_changed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('phone_number', sa.VARCHAR(length=9), autoincrement=False, nullable=True),
    sa.Column('preferred_contact_method', postgresql.ENUM('any', 'phone', 'email', 'pm', name='contactmethods'), autoincrement=False, nullable=False),
    sa.Column('profile_picture_file_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_of_birth', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name='profile_creator_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='profile_pkey'),
    sa.UniqueConstraint('creator_id', name='profile_creator_id_key')
    )
    # ### end Alembic commands ###
